### ISSUE TITLE
TODO for V1

### ISSUE THREAD

**Issue by dani007200964** [dani007200964/Viking-Skull-Lamp#4]
Before publication:
- [x] Check links in the documentation
- [x] Create a YouTube description
- [x] Upload the files to Printables
- [x] Grammar check
- [x] Fix video orientations
- [x] Document the rest of the code
- [x] Readme
- [x] Model material fix
- [x] Documentation link in readme

After publication:
- [x] Readme documentation link.
- [x] Printables documentation link
- [x] Youtube documentation link
- [x] Check badge on software section
